export const ENDPOINTS = {
  auth: { login: '/auth/login', me: '/auth/me' },
  vehicles: '/vehicles',
  drivers: '/drivers',
  trips: '/trips',
  maintenance: '/maintenance',
  fuelLogs: '/fuel-logs',
  expenses: '/expenses',
  dashboard: '/dashboard/kpis',
  reports: {
    fuelEfficiency: '/reports/fuel-efficiency',
    operationalCost: '/reports/operational-cost',
    roi: '/reports/roi',
    monthlyRevenue: '/reports/monthly-revenue',
    export: (type) => `/reports/export/${type}`,
  },
  regions: '/regions',
  settings: '/settings',
  rolePermissions: '/roles/permissions',
};
